### PR TITLE
fix(gemini): retry at rate limit

### LINKED ISSUE #467: Gemini API would silently terminate when reaching its rate limit
### Describe the bug

As the title says (see screenshot).

### Setup

Please complete the following information along with version numbers, if applicable.
 - OS [e.g. Ubuntu, macOS]: Ubuntu (WSL2)
 - Shell [e.g. zsh, fish]: zsh
 - Terminal Emulator [e.g. kitty, iterm]: Windows Terminal
 - Terminal Multiplexer [e.g. tmux]: None

*Note: you might encounter rendering issues if your locale does not use
`UTF-8` encoding. Please check your locale (`locale` on POSIX systems) to
see what encoding is being used by your system.*

### To Reproduce

1. Cause a rate limit with the Gemini API 😅
2. Send a message to Crush
3. Crush would terminate silently 

### Source Code

Please include a [minimum reproducible example][writing-example] to reproduce the behavior.

Please paste your example as a code block on the issue. Do not link to an external project. Your example should fit in a single file. Take a look at [Bubble Tea examples][bubbletea-example] for an idea on writing a small, but runnable program.

[bubbletea-example]: https://github.com/charmbracelet/bubbletea/tree/main/examples
[writing-example]: https://stackoverflow.com/help/minimal-reproducible-example

### Expected behavior

Show a rate limit error.

### Screenshots

Image

### Additional context

I will open a PR to fix this!

### PR DESCRIPTION
**Pull request by ras0q**
### Describe your changes

fix #467

Previously, Gemini API would silently terminate when reaching its rate limit.

Before|After
-|-
image|image

### Checklist before requesting a review

- [x] I have read [`CONTRIBUTING.md`](https://github.com/charmbracelet/.github/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my code

### If this is a feature

- [ ] I have created a discussion
- [ ] A project maintainer has approved this feature request. Link to comment:

### CODE REVIEW

File: internal/llm/provider/gemini.go [hunk 1]
```diff
@@ -327,7 +327,7 @@ func (g *geminiClient) stream(ctx context.Context, messages []message.Message, t
 						return
 					}
 					if retry {
-						slog.Warn("Retrying due to rate limit", "attempt", attempts, "max_retries", maxRetries)
+						slog.Warn("Retrying due to rate limit", "attempt", attempts, "max_retries", maxRetries, "after_ms", after)
```
Comment (ras0q) [inline internal/llm/provider/gemini.go:330]: Since the retry time gradually increases, I think it would be helpful to output it to the log. What do you think about this?

**Review by meowgorithm — APPROVED** [review]

**Comment by meowgorithm** [comment]
You're wonderful, @ras0q. Thank you!
